### ISSUE TITLE
Error: Failed to execute program org.gnome.Shell.Extensions: No such file or directory

### ISSUE THREAD

**Issue by ghost** [flathub/org.gnome.Extensions#13]
Hi, I just installed from Flathub and it's not working anymore...

- OS: Ubuntu 22.10
- org.gnome.Extensions version: 43.0 via Flathub 

My verbose

```
LC_ALL=C flatpak run --verbose org.gnome.Extensions
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/sabri/.local/share/flatpak
F: Opening user flatpak installation at path /home/sabri/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/org.gnome.Extensions/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/sabri/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/43/171d01a0888ca840cbf55bc8b7f7101bcb10ae445d3ff5210563330ce87d3b8e/files/lib32 does not exist
F: Allocated instance id 2246364508
F: Add defaults in dir /org/gnome/Extensions/
F: Add locks in dir /org/gnome/Extensions/
F: Disallowing network access
F: Allowing dri access
F: Allowing host-fs access
F: skipping export for path /usr/libx32 in unsupported prefix
F: Unable to open path /run/media to export read/write: No such file or directory
F: Allowing homedir access
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 40 gnome-extensions-app'

(gnome-extensions-app:3): Gjs-CRITICAL **: 03:02:21.870: JS ERROR: Gio.DBusError: Error calling StartServiceByName for org.gnome.Shell.Extensions: Failed to execute program org.gnome.Shell.Extensions: No such file or directory
_injectToMethod/klass[method]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:287:25
_makeProxyWrapper/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:264:17
vfunc_startup@resource:///org/gnome/Extensions/js/main.js:69:28
main@resource:///org/gnome/Extensions/js/main.js:547:23
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/app/share/gnome-extensions-app/org.gnome.Extensions:1:17


(gnome-extensions-app:3): Gjs-CRITICAL **: 03:02:21.870: JS ERROR: TypeError: this._shellProxy is undefined
vfunc_activate@resource:///org/gnome/Extensions/js/main.js:54:9
main@resource:///org/gnome/Extensions/js/main.js:547:23
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/app/share/gnome-extensions-app/org.gnome.Extensions:1:17

```

**Comment by fmuellner** [comment]
Is that the regular Ubuntu edition (using GNOME)?

`org.gnome.Shell.Extensions` is the D-Bus service that GNOME provides for managing extensions. The app should handle the case where the service isn't available better, but the best it can do in that case is display an error that it isn't working.

**Comment by ghost** [comment]
Regular Ubuntu 22.10 (the latest version), I use GNOME session instead Ubuntu session. 

If you have the extension both from Deb and Flatpak -> Flatpak version runs.
If you only have Flatpak -> This error happening.

I'll check on a clean Ubuntu install today.

**Comment by fmuellner** [comment]
> If you have the extension both from Deb and Flatpak -> Flatpak version runs.

Mmh, that would suggest that the D-Bus service is somehow split out and pulled in as a dependency by the Extensions deb.

But according to [packages.ubuntu.com](https://packages.ubuntu.com/kinetic/gnome-shell), that's not the case.

**Comment by ghost** [comment]
I found the problem. It is related to **gjs** dependence.

On ubuntu, gnome-shell-extension-prefs depends on **gjs**. If I purg this package and remove orphan packages, I end up removing gjs dependence. 

On Flatpak/Flathub side we don't need to do anything. On the extension side, the developer may add a better warning about missing gjs.

**Comment by fmuellner** [comment]
> On ubuntu, gnome-shell-extension-prefs depends on **gjs**. If I purg this package and remove orphan packages, I end up removing gjs dependence.

OK, that is a bug.

gnome-shell itself (the executable) links to libgjs and doesn't need the gjs executable, but all the D-Bus services that are installed along-side gnome-shell do.

Can you report that issue to Ubuntu?

**Comment by ghost** [comment]
I reported to Ubuntu. Could you give extra information and your opinion to Ubuntu team.

https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1993831

**Comment by fmuellner** [comment]
I don't have a launchpad account ...

But note that the issue is not really flatpak specific. Anything that tries to access a D-Bus service provided by gnome-shell will fail when gjs is not installed.

**Comment by ghost** [comment]
I can link your comment there if you share it here. I usually just use and
translate applications. I don't have enough knowledge about D-Bus or other
deep topics.

**Comment by fmuellner** [comment]
gnome-shell includes some small external D-Bus services - namely org.gnome.Shell.Extensions.service, org.gnome.Shell.Notifications.service and org.gnome.Shell.Screencast.service - that require the standalone gjs executable. The package that provides /usr/bin/gjs should therefore be a dependency of the package that includes those services (gnome-shell/gnome-shell-common).
