### ISSUE TITLE
Extensions order

### ISSUE THREAD

**Issue by ilippert** [flathub/org.gnome.Extensions#4]
I like the app to manage the extensions individually. What I miss is the ability to reorder them, i.e. change how the extensions sit next to each other. I would love to see the ability to drag and drop the extensions into an order that is helpful for my purposes. I guess a similar function was available once upon a time via https://extensions.gnome.org/extension/2114/order-gnome-shell-extensions/

**Comment by fmuellner** [comment]
That would require injecting code into gnome-shell, which isn't really anything any app should do. This is particular the case when distributed as flatpak, as injecting code into the compositor defies any notion of sandboxing.

But even ignoring those more technical points, the Extensions app isn't the right place for such a feature. Not all extensions add an icon to the top bar, so the concept of "extension order" doesn't generally make sense. For example "dash-to-dock before cover-flow" makes no sense at all.


> I guess a similar function was available once upon a time via https://extensions.gnome.org/extension/2114/order-gnome-shell-extensions/

It looks like the extension is meant to be compatible with GNOME 40, it just erroneously states the version as "3.40" in its metadata. That hardly qualifies as "once upon a time" ;-)

**Comment by ilippert** [comment]
Thanks for the comment and explanation
