### ISSUE TITLE
org.gnome.Extensions (from flathub) does not use GTK theme

### ISSUE THREAD

**Issue by Mershl** [flathub/org.gnome.Extensions#9]
Tested quite a lot of GNOME apps from flathub using `yaru-dark-theme` (enabled via `gnome-tweaks`). Flatpak will automatically install the `org.gtk.Gtk3theme.Yaru-dark` runtime. This theme will then be used for most (all tested so far, except Extensions) org.gnome.* apps from Flathub.

org.gnome.Extensions does not use the theme. Screenshot:
![image](https://user-images.githubusercontent.com/520251/135715009-4f657f75-8179-4484-93a6-0a7e84c72a24.png)

Example org.gnome.Logs (from flathub):
![image](https://user-images.githubusercontent.com/520251/135714999-cc3085ea-1c1d-4099-aceb-2df87d441071.png)

Example org.gnome.Weather (from flathub):
![image](https://user-images.githubusercontent.com/520251/135715162-0f9456f3-b0b4-42b9-a0f4-057c22616e41.png)

**Comment by fmuellner** [comment]
> Flatpak will automatically install the `org.gtk.Gtk3theme.Yaru-dark` runtime. This theme will then be used for most (all tested so far, except Extensions)

That is because Extensions was ported to GTK4. If `org.gtk.Gtk4theme.Yaru-dark` exists, it should be used. But GTK3 themes won't work.

**Comment by beedell-roke** [comment]
https://github.com/flatpak/flatpak/issues/4605#issue-1068984840

**Comment by fmuellner** [comment]
I'll note that in the meantime the app has been ported to libadwaita, so GTK4 themes no longer work regardless of packaging.
